name: Build & Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        path: code
    - name: Checkout site
      uses: actions/checkout@v2
      with: 
        token: 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
        repository: dharmeshchowdhary/personal-website-public
        ref: main 
        path: https://dharmeshchowdhary.github.io/personal-website-public/
    - name: Perform jekyll build
      uses: helaili/jekyll-action@v2
      with:
        jekyll_env: prod
        jekyll_src: code
        build_only: true
    - name: Clean website
      run: |
        pushd site
        git rm -rf .
        popd
    - name: Copy site
      run: |
        pushd site
        cp -rvf ../code/build/* . 
        popd
        ls -la site/ 
    - name: Publish
      run: |
        git config --global user.email "dharmeshchowdhary2000@gmail.com"
        git config --global user.name "dharmeshchowdhary"
        pushd site 
        git add . 
        git commit -m "jekyll build from Action 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" 
        git push origin main
        popd
